spring.application.name=invoice-management
# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/invoicemanagement
spring.datasource.username=postgres
spring.datasource.password=apurv998
spring.datasource.driver-class-name=org.postgresql.Driver
# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# PostgreSQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# Server Port
server.port=8080
jwt.secret=MySecretSuperKeyMySecretSuperKeyMysecretSuperkey12345
jwt.expiration=86400000